services:
  station-webapp:
    build: .
    image: station-webapp
    container_name: station-webapp
    ports:
      - "8080:80"
    depends_on:
      - station-api-server
  station-api-server:
    build: ../api-server
    image: station-relay-server
    container_name: station-api-server
    environment:
      - RUST_LOG=info
      - PORT=3000
