services:
  station-relay-server:
    build: ../relay-server
    image: station-relay-server
    container_name: station-relay-server
    environment:
      - CORS_ORIGIN=*
      - RUST_LOG=debug
      - PORT=3000
  station-webapp:
    build: .
    image: station-webapp
    container_name: station-webapp
    ports:
      - "8080:80"
    depends_on:
      - station-relay-server
